# Generated by Django 4.1.2 on 2022-11-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='posts',
            name='VedioPost',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
