# Generated by Django 4.1.2 on 2022-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_alter_posts_options_posts_vediopost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='VedioPost',
            field=models.FileField(null=True, upload_to='vedios/'),
        ),
    ]
