# Generated by Django 4.1.2 on 2022-11-11 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_posts_updated_date_alter_posts_vediopost'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='Blog_Post', to=settings.AUTH_USER_MODEL),
        ),
    ]
