# Generated by Django 4.1.2 on 2022-11-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_posts_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defuilt/avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
