# Generated by Django 4.1.2 on 2022-11-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0007_remove_posts_profile_pic_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='PhotePost',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
